
'use client';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { AppWindow, ChefHat, ClipboardEdit, ArrowRight, Edit, Youtube, BookOpenText, Calculator } from 'lucide-react';
import Image from 'next/image';
import Link from 'next/link';

// Apps that are considered "finished" or more complete
const apps = [
  { 
    title: "AI Meal Creator", 
    description: "Input your ingredients and preferences to get AI-generated meal ideas and recipes.", 
    href: "/meal-creator",
    icon: <ChefHat className="h-8 w-8 mb-2 text-primary" />,
    imageSrc: "https://placehold.co/600x400.png",
    imageHint: "food cooking",
  },
  { 
    title: "AI Project Document Creator", 
    description: "Define your project's parameters or describe your vision to get a comprehensive Project Management Document (PMD) generated by AI.", 
    href: "/project-maker",
    icon: <ClipboardEdit className="h-8 w-8 mb-2 text-primary" />,
    imageSrc: "https://placehold.co/600x400.png",
    imageHint: "project planning document",
  },
  {
    title: "Calculator",
    description: "A versatile calculator with standard, scientific, and basic graphing modes.",
    href: "/calculator",
    icon: <Calculator className="h-8 w-8 mb-2 text-primary" />,
    imageSrc: "https://placehold.co/600x400.png",
    imageHint: "math numbers calculation",
  },
  {
    title: "Deal Out - AI Editor",
    description: "A next-generation word processor with AI-assisted writing, refinement, and composition tools.",
    href: "/deal-out",
    icon: <Edit className="h-8 w-8 mb-2 text-primary" />,
    imageSrc: "https://placehold.co/600x400.png",
    imageHint: "writing document editor",
  },
  { 
    title: "Hangout Helper", 
    description: "Discover exciting hangout ideas with AI-powered suggestions, saved lists, and scavenger hunt generation.", 
    href: "/", // This is the Home page
    icon: <AppWindow className="h-8 w-8 mb-2 text-primary" />,
    imageSrc: "https://placehold.co/600x400.png",
    imageHint: "friends fun",
  },
  {
    title: "Lesson Plan Maker",
    description: "Craft detailed lesson plans using an AI assistant aware of various educational frameworks and age-specific needs, with biblical integration.",
    href: "/lesson-plan-maker",
    icon: <BookOpenText className="h-8 w-8 mb-2 text-primary" />,
    imageSrc: "https://placehold.co/600x400.png",
    imageHint: "education planning teaching",
  },
  {
    title: "YouTube Video Chat",
    description: "Enter a YouTube video link to fetch its transcript and chat with an AI about its content.",
    href: "/youtube-chat",
    icon: <Youtube className="h-8 w-8 mb-2 text-primary" />,
    imageSrc: "https://placehold.co/600x400.png",
    imageHint: "video chat play",
  },
];

export default function OtherAppsPage() {
  return (
    <div className="space-y-12">
      <section className="text-center py-8 bg-card shadow-lg rounded-xl border">
        <AppWindow className="mx-auto h-16 w-16 text-primary mb-4" />
        <h1 className="text-4xl font-bold tracking-tight text-foreground mb-3">
          Discover Our Applications
        </h1>
        <p className="text-muted-foreground max-w-xl mx-auto">
          Explore the suite of AI-powered tools designed to help you with various tasks. 
          Some experimental apps are listed under "In Development".
        </p>
      </section>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {apps.sort((a,b) => a.title.localeCompare(b.title)).map((app, index) => (
          <Card key={index} className="shadow-md hover:shadow-lg transition-shadow duration-300 ease-in-out border flex flex-col">
            <CardHeader className="items-center text-center">
              {app.icon}
              <CardTitle className="text-2xl">{app.title}</CardTitle>
            </CardHeader>
            <CardContent className="flex-grow flex flex-col">
              <Image
                src={app.imageSrc}
                alt={`Placeholder for ${app.title}`}
                data-ai-hint={app.imageHint}
                width={600}
                height={400}
                className="mb-4 rounded-md aspect-video object-cover"
              />
              <CardDescription className="text-muted-foreground text-sm mb-4 flex-grow">
                {app.description}
              </CardDescription>
              <Button asChild variant="outline" className="mt-auto w-full">
                <Link href={app.href}>
                  Open App
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Link>
              </Button>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
