
'use client';

import * as React from 'react'; // Added React import
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { ArrowRight, AppWindow, ChefHat, ClipboardEdit, Edit, Youtube, BookOpenText, Calculator, Settings2, DraftingCompass, Music, Brain, Link as LinkLucideIcon, LightbulbIcon, DollarSign, CheckCircle } from 'lucide-react';
import Image from 'next/image';
import Link from 'next/link';

// Re-using app definitions for showcase
const publishedApps = [
  {
    title: "AI Meal Creator",
    description: "Input your ingredients and preferences to get AI-generated meal ideas and recipes.",
    href: "/meal-creator",
    icon: <ChefHat className="h-8 w-8 mb-2 text-primary" />,
    imageSrc: "https://placehold.co/600x400.png",
    imageHint: "food cooking",
  },
  {
    title: "AI Project Document Creator",
    description: "Define your project's parameters or describe your vision to get a comprehensive Project Management Document (PMD) generated by AI.",
    href: "/project-maker",
    icon: <ClipboardEdit className="h-8 w-8 mb-2 text-primary" />,
    imageSrc: "https://placehold.co/600x400.png",
    imageHint: "project planning document",
  },
  {
    title: "Calculator",
    description: "A versatile calculator with standard, scientific, and basic graphing modes.",
    href: "/calculator",
    icon: <Calculator className="h-8 w-8 mb-2 text-primary" />,
    imageSrc: "https://placehold.co/600x400.png",
    imageHint: "math numbers calculation",
  },
  {
    title: "Deal Out - AI Editor",
    description: "A next-generation word processor with AI-assisted writing, refinement, and composition tools.",
    href: "/deal-out",
    icon: <Edit className="h-8 w-8 mb-2 text-primary" />,
    imageSrc: "https://placehold.co/600x400.png",
    imageHint: "writing document editor",
  },
  {
    title: "Hangout Helper",
    description: "Discover exciting hangout ideas with AI-powered suggestions, saved lists, and scavenger hunt generation.",
    href: "/hangout-helper", // New route for Hangout Helper
    icon: <LightbulbIcon className="h-8 w-8 mb-2 text-primary" />, // Changed icon
    imageSrc: "https://placehold.co/600x400.png",
    imageHint: "friends fun",
  },
  {
    title: "Lesson Plan Maker",
    description: "Craft detailed lesson plans using an AI assistant aware of various educational frameworks and age-specific needs, with biblical integration.",
    href: "/lesson-plan-maker",
    icon: <BookOpenText className="h-8 w-8 mb-2 text-primary" />,
    imageSrc: "https://placehold.co/600x400.png",
    imageHint: "education planning teaching",
  },
  {
    title: "YouTube Video Chat",
    description: "Enter a YouTube video link to fetch its transcript and chat with an AI about its content.",
    href: "/youtube-chat",
    icon: <Youtube className="h-8 w-8 mb-2 text-primary" />,
    imageSrc: "https://placehold.co/600x400.png",
    imageHint: "video chat play",
  },
];

const developmentApps = [
  {
    title: "Drafting Board",
    description: "A simple 2D drafting tool for creating basic architectural plans and diagrams. Features grid snapping.",
    href: "/drafting-board",
    icon: <DraftingCompass className="h-8 w-8 mb-2 text-primary" />,
    imageSrc: "https://placehold.co/600x400.png",
    imageHint: "architecture drawing blueprint",
  },
  {
    title: "Chromatic Tuner",
    description: "Tune your instruments with a chromatic tuner and generate reference tones. Features QWERTY piano.",
    href: "/chromatic-tuner",
    icon: <Music className="h-8 w-8 mb-2 text-primary" />,
    imageSrc: "https://placehold.co/600x400.png",
    imageHint: "music guitar tuning",
  },
  {
    title: "Study Guide Creator",
    description: "Turn any text content into a deep study guide, complete with flashcards, definitions, and practice questions.",
    href: "/study-guide-creator",
    icon: <Brain className="h-8 w-8 mb-2 text-primary" />,
    imageSrc: "https://placehold.co/600x400.png",
    imageHint: "learning study books",
  },
  {
    title: "Link Chat",
    description: "Paste any web page link to attempt to fetch its HTML content, then chat with an AI about what's on the page.",
    href: "/link-chat",
    icon: <LinkLucideIcon className="h-8 w-8 mb-2 text-primary" />,
    imageSrc: "https://placehold.co/600x400.png",
    imageHint: "web browsing chat",
  },
];

const allTools = [...publishedApps, ...developmentApps].sort((a, b) => a.title.localeCompare(b.title));


export default function LandingPage() {
  return (
    <div className="space-y-16">
      <section className="text-center py-12 md:py-20 bg-gradient-to-br from-primary/10 via-background to-background border-b">
        <AppWindow className="mx-auto h-20 w-20 text-primary mb-6 animate-pulse" />
        <h1 className="text-4xl sm:text-5xl md:text-6xl font-bold tracking-tight text-foreground mb-6">
          Unlock Your Creativity with <span className="text-primary">Beautiful Ideas</span>
        </h1>
        <p className="text-lg sm:text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">
          Access our entire catalog of innovative AI-powered tools, ready to embed in your website or use directly.
        </p>
        <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-10">
          <Button size="lg" className="text-lg px-8 py-6 shadow-lg hover:shadow-xl transition-shadow w-full sm:w-auto">
            <DollarSign className="mr-2 h-6 w-6" />
            Join Now - $10/month
          </Button>
          <Button size="lg" variant="outline" className="text-lg px-8 py-6 w-full sm:w-auto">
            Explore Tools
            <ArrowRight className="ml-2 h-5 w-5" />
          </Button>
        </div>
         <p className="text-sm text-muted-foreground">
          One simple subscription. Unlimited access to all current and future tools.
        </p>
      </section>

      <section className="py-12 md:py-16">
        <div className="text-center mb-12">
          <h2 className="text-3xl sm:text-4xl font-bold tracking-tight text-foreground">Our Suite of Embeddable Tools</h2>
          <p className="mt-4 text-lg text-muted-foreground max-w-xl mx-auto">
            Powerful, AI-driven applications designed to enhance your projects and workflows.
          </p>
        </div>
        {allTools.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {allTools.map((app) => (
              <Card key={app.title} className="shadow-lg hover:shadow-xl transition-shadow duration-300 ease-in-out border flex flex-col overflow-hidden group">
                <div className="relative aspect-video w-full overflow-hidden">
                  <Image
                    src={app.imageSrc}
                    alt={`Showcase for ${app.title}`}
                    data-ai-hint={app.imageHint}
                    layout="fill"
                    objectFit="cover"
                    className="group-hover:scale-105 transition-transform duration-300"
                  />
                   <div className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent"></div>
                   <div className="absolute bottom-4 left-4 text-white">
                      {React.cloneElement(app.icon as React.ReactElement<any>, { className: "h-10 w-10 mb-2 opacity-80"})}
                     <CardTitle className="text-2xl drop-shadow-md">{app.title}</CardTitle>
                   </div>
                </div>
                <CardContent className="p-6 flex-grow flex flex-col">
                  <CardDescription className="text-muted-foreground text-sm mb-4 flex-grow">
                    {app.description}
                  </CardDescription>
                  <Button asChild variant="secondary" className="mt-auto w-full group-hover:bg-primary group-hover:text-primary-foreground transition-colors">
                    <Link href={app.href}>
                      Learn More & Access
                      <ArrowRight className="ml-2 h-4 w-4" />
                    </Link>
                  </Button>
                </CardContent>
              </Card>
            ))}
          </div>
        ) : (
          <p className="text-center text-muted-foreground">No tools available at the moment. Check back soon!</p>
        )}
      </section>

      <section className="py-12 md:py-16 bg-muted/50 rounded-xl border">
        <div className="container mx-auto px-4">
          <div className="text-center mb-10">
            <h2 className="text-3xl sm:text-4xl font-bold tracking-tight text-foreground">Why Choose Beautiful Ideas?</h2>
          </div>
          <div className="grid md:grid-cols-3 gap-8">
            <div className="flex flex-col items-center text-center p-6">
              <CheckCircle className="h-12 w-12 text-primary mb-4" />
              <h3 className="text-xl font-semibold mb-2">All-Access Pass</h3>
              <p className="text-muted-foreground">One subscription unlocks every tool in our growing library. Simple and affordable.</p>
            </div>
            <div className="flex flex-col items-center text-center p-6">
              <CheckCircle className="h-12 w-12 text-primary mb-4" />
              <h3 className="text-xl font-semibold mb-2">Embed Anywhere</h3>
              <p className="text-muted-foreground">Easily integrate our tools into your existing website or platform (coming soon).</p>
            </div>
            <div className="flex flex-col items-center text-center p-6">
              <CheckCircle className="h-12 w-12 text-primary mb-4" />
              <h3 className="text-xl font-semibold mb-2">Constantly Evolving</h3>
              <p className="text-muted-foreground">We're always developing new tools and improving existing ones based on your feedback.</p>
            </div>
          </div>
           <div className="text-center mt-10">
              <Button size="lg" className="text-lg px-10 py-6 shadow-lg hover:shadow-xl transition-shadow">
                Get Started for $10/month
              </Button>
            </div>
        </div>
      </section>
    </div>
  );
}

